apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: client-build
objects:
  - apiVersion: "v1"
    kind: ImageStream
    metadata:
      name: node
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: docker.io/node:13.7-alpine3.11
          name: "1"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: dotnet-21-rhel7
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: registry.redhat.io/dotnet/dotnet-21-rhel7:2.1-41
          name: "2.1-41"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
      postCommit: {}
      source:
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: "${DOTNET_STARTUP_PROJECT}"
          dockerfilePath: "${DOCKER_FILE_PATH}"
parameters:
  - description: Name of the project (SCHOOLBUS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "hets"
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: false
    value: "client"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: "1.0"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ""
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: "master"
  - name: DOCKER_FILE_PATH
    displayName: Docker File Path
    description: The path to the docker file defining the build.
    required: false
    value: "client/Dockerfile"
  - name: DOTNET_STARTUP_PROJECT
    displayName: DotNet Startup Project
    description: The path to the startup project for the .Net application.
    required: true
    value: "FrontEnd/FrontEnd/FrontEnd.csproj"