kind: Template
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
labels:
  template: client-app-build
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
      postCommit: {}
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: client:${VERSION}
          dockerfilePath: "${DOCKER_FILE_PATH}"
parameters:
  - description: Name of the project (HETS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "het"
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: client-app
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: "1.9.3"
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/bcgov/hets.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: ''
  - name: DOCKER_FILE_PATH
    displayName: Docker File Path
    description: The path to the docker file defining the build.
    required: false
    value: frontend.Dockerfile